# Generated by Django 4.0.4 on 2022-12-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MVT_APP', '0002_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
