# Generated by Django 4.0.4 on 2022-12-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVT_APP', '0008_libro_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/imagenes/portadas'),
        ),
    ]
